name: GitHub Actions Demo
on: [push]
jobs:
  windows-action:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: compile-rust
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: compile-vs
        uses: ilammy/msvc-dev-cmd@v1.4.1
      # - run: Invoke-WebRequest "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/VisualStudioClient/vsextensions/MicrosoftVisualStudio2017InstallerProjects/1.0.0/vspackage" -OutFile ./installerExtenxion.vsix
      # - run: VSIXInstaller.exe installerExtension.vsix
      - run: | 
          msbuild.exe winage\age.sln /property:Configuration=Release /property:Platform=x64
      - run: echo "ğŸ This job's status is ${{ job.status }}."

      
      # - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}